### PR TITLE
Support Amazon Linux 2023

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
Marking as draft while I validate with some modules that need to support Amazon 2023.

**Comment by treydock** [comment]
This won't work for all cases until https://github.com/puppetlabs/beaker-puppet/commit/6063d22b6c4449df795731f5853c3c75241240c4 is tagged.

**Comment by treydock** [comment]
This is working.  https://github.com/OSC/puppet-module-openondemand/actions/runs/7656172797/job/20863882254

The job itself is failing but that's because the RPM repos I'm testing against don't yet exist but the beaker parts to bootstrap the tests are working for Amazon 2023.

**Review by ekohl — APPROVED** [review]
I missed this one, but looks good.

**Pull request merged**
