### PR TITLE
Added ENV DOCKER_IN_DOCKER to fix SSH conn info

### LINKED ISSUE #46: rake beaker fail when using beaker-docker 0.8.4 in a docker in docker environment
We have a Jenkins job configured to run `bundle exec rake beaker` in a docker in docker setup.
This started to fail as beaker-docker was updated from 0.8.3 to 0.8.4...

It looks like it is trying to ssh into the docker host  on port 22 `Using container connection at 172.17.0.1:22`
With 0.8.3 it seems to ssh into the SUT ip `Using container connection at 172.17.0.7:22`

```
11:33:18  TEST_TIERS env variable not defined. Defaulting to run all tests.
11:33:18  /home/jenkins/.rbenv/versions/2.5.3/bin/ruby -I/home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib:/home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-support-3.10.2/lib /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/exe/rspec spec/acceptance
11:33:20  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-rspec-6.3.0/lib/beaker-rspec/helpers/serverspec.rb:43: warning: already initialized constant Module::VALID_OPTIONS_KEYS
11:33:20  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/specinfra-2.82.2/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here
11:33:20  Hypervisor for centos-7-x64 is docker
11:33:20  Beaker::Hypervisor, found some docker boxes to create
11:33:20  Provisioning docker
11:33:20  provisioning centos-7-x64
11:33:20  Creating image
11:33:20  Dockerfile is         FROM centos:7
11:33:20          ENV container docker
11:33:20  RUN yum clean all
11:33:20  RUN yum install -y sudo openssh-server openssh-clients curl ntpdate
11:33:20  RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
11:33:20  RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
11:33:20  RUN sed 's@session *required *pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/*
11:33:20  RUN mkdir -p /var/run/sshd
11:33:20  RUN echo root:root | chpasswd
11:33:20  RUN sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
11:33:20  RUN sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
11:33:20  RUN sed -ri 's/^#?UseDNS .*/UseDNS no/' /etc/ssh/sshd_config
11:33:20  RUN yum install -y epel-release
11:33:20  RUN yum install -y iproute java-1.8.0-openjdk unzip wget which awk jq
11:33:20          EXPOSE 22
11:33:20          CMD ["/usr/sbin/init"]
11:33:20  Docker build buildargs: {}
11:33:20  post
11:33:20  /build
11:33:20  {:rm=>true, :buildargs=>"{}"}
11:33:20  Dockerfile0000640000000000000000000000141414027063357013313 0ustar00wheelwheel00000000000000        FROM centos:7
11:33:20          ENV container docker
11:33:20  RUN yum clean all
11:33:20  RUN yum install -y sudo openssh-server openssh-clients curl ntpdate
11:33:20  RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
11:33:20  RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
11:33:20  RUN sed 's@session *required *pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/*
11:33:20  RUN mkdir -p /var/run/sshd
11:33:20  RUN echo root:root | chpasswd
11:33:20  RUN sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
11:33:20  RUN sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
11:33:20  RUN sed -ri 's/^#?UseDNS .*/UseDNS no/' /etc/ssh/sshd_config
11:33:20  RUN yum install -y epel-release
11:33:20  RUN yum install -y iproute java-1.8.0-openjdk unzip wget which awk jq
11:33:20          EXPOSE 22
11:33:20          CMD ["/usr/sbin/init"]
11:33:20  
11:33:20  Creating container from image 0fabfb43f0d8
11:33:20  post
11:33:20  /containers/create
11:33:20  {"name"=>"beaker-centos-7-x64-f5415fab2076"}
11:33:20  {"Image":"0fabfb43f0d8","Hostname":"centos-7-x64","HostConfig":{"PortBindings":{"22/tcp":[{"HostPort":"1262","HostIp":"0.0.0.0"}]},"PublishAllPorts":true,"RestartPolicy":{"Name":"always"},"Privileged":true}}
11:33:20  get
11:33:20  /containers/b3cd06788404a0d0891d0ae83156d3aad65ca5a940b81d6cb62148e087fbc089/json
11:33:20  {}
11:33:20  
11:33:20  get
11:33:20  /info
11:33:20  {}
11:33:20  
11:33:20  Starting container b3cd06788404a0d0891d0ae83156d3aad65ca5a940b81d6cb62148e087fbc089
11:33:20  post
11:33:20  /containers/b3cd06788404a0d0891d0ae83156d3aad65ca5a940b81d6cb62148e087fbc089/start
11:33:20  {}
11:33:20  {}
11:33:20  get
11:33:20  /containers/b3cd06788404a0d0891d0ae83156d3aad65ca5a940b81d6cb62148e087fbc089/stats
11:33:20  {:stream=>0}
11:33:20  
11:33:22  get
11:33:22  /containers/b3cd06788404a0d0891d0ae83156d3aad65ca5a940b81d6cb62148e087fbc089/json
11:33:22  {}
11:33:22  
11:33:22  Using container connection at 172.17.0.1:22
11:33:22  node available as ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@172.17.0.1 -p 22
11:33:22  get
11:33:22  /containers/b3cd06788404a0d0891d0ae83156d3aad65ca5a940b81d6cb62148e087fbc089/json
11:33:22  {}
11:33:22  
11:33:22  
11:33:22  centos-7-x64 11:33:21$ cat /etc/resolv.conf
11:33:22    Attempting ssh connection to 172.17.0.1, user: root, opts: {:password=>"root", :port=>"22", :forward_agent=>false, :auth_methods=>["password", "publickey", "hostbased", "keyboard-interactive"]}
11:33:25  root@172.17.0.1's password:Inappropriate ioctl for device
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/net-ssh-6.1.0/lib/net/ssh/prompt.rb:45:in `noecho'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/net-ssh-6.1.0/lib/net/ssh/prompt.rb:45:in `ask'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/password.rb:68:in `ask_password'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/password.rb:21:in `authenticate'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:86:in `block in authenticate'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `each'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `authenticate'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:255:in `start'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/ssh_connection.rb:81:in `connect_block'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/ssh_connection.rb:111:in `connect'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/ssh_connection.rb:43:in `connect'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/host.rb:302:in `connection'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/host.rb:362:in `block (2 levels) in exec'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/logger.rb:239:in `with_indent'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/host.rb:361:in `block in exec'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/host.rb:360:in `exec'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/host_prebuilt_steps.rb:292:in `get_domain_name'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/host_prebuilt_steps.rb:392:in `block in hack_etc_hosts'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/host_prebuilt_steps.rb:389:in `each'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/host_prebuilt_steps.rb:389:in `hack_etc_hosts'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-docker-0.8.4/lib/beaker/hypervisor/docker.rb:337:in `provision'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/hypervisor.rb:37:in `create'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/network_manager.rb:72:in `block in provision'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/network_manager.rb:71:in `each_key'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-4.26.0/lib/beaker/network_manager.rb:71:in `provision'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-rspec-6.3.0/lib/beaker-rspec/beaker_shim.rb:35:in `provision'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-rspec-6.3.0/lib/beaker-rspec/spec_helper.rb:57:in `block in <top (required)>'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core.rb:98:in `configure'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-rspec-6.3.0/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-rspec-6.3.0/lib/beaker-rspec.rb:5:in `require'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-rspec-6.3.0/lib/beaker-rspec.rb:5:in `<module:BeakerRSpec>'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/beaker-rspec-6.3.0/lib/beaker-rspec.rb:1:in `<top (required)>'
11:33:25  /home/jenkins/workspace/_test-versjoner-av-beaker-docker/spec/spec_helper_acceptance.rb:7:in `require'
11:33:25  /home/jenkins/workspace/_test-versjoner-av-beaker-docker/spec/spec_helper_acceptance.rb:7:in `<top (required)>'
11:33:25  /home/jenkins/workspace/_test-versjoner-av-beaker-docker/spec/acceptance/01_am__client_spec.rb:1:in `require'
11:33:25  /home/jenkins/workspace/_test-versjoner-av-beaker-docker/spec/acceptance/01_am__client_spec.rb:1:in `<top (required)>'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2112:in `load'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2112:in `load_file_handling_errors'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1615:in `block in load_spec_files'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1613:in `each'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1613:in `load_spec_files'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:102:in `setup'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
11:33:25  /home/jenkins/.rbenv/versions/2.5.3/bin/ruby -I/home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/lib:/home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-support-3.10.2/lib /home/jenkins/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rspec-core-3.10.1/exe/rspec spec/acceptance failed

```

### PR DESCRIPTION
**Pull request by QueerCodingGirl**
This fixes #46 for my docker-in-docker gitlab runner setup.

### CODE REVIEW

**Comment by ekohl** [comment]
@h-haaks does https://github.com/voxpupuli/beaker-docker/issues/46#issuecomment-899886704 imply you've tested this? If so, can you approve this PR?

**Comment by h-haaks** [comment]
@ekohl I have tested this branch in our Jenkins setup ( docker in docker ) and locally ( plain docker ) and confirm that it solves #46.
The new env var DOCKER_IN_DOCKER needs to be documented i guess.

**Comment by h-haaks** [comment]
I don't think I'm allowed to approve PRs ...

**Comment by ekohl** [comment]
Now it's a bit of bookkeeping (and the current comment is sufficient), but for the record, any logged in user is able to go to https://github.com/voxpupuli/beaker-docker/pull/51/files and use the `Review changes` button to approve. If you don't have permissions, then it'll show up as gray, otherwise as green.

**Review by h-haaks — APPROVED** [review]

**Comment by ekohl** [comment]
I'd be OK with merging this, but I do agree this part would be nice to fix:

>  The new env var DOCKER_IN_DOCKER needs to be documented i guess.

**Review by ekohl — APPROVED** [review]
Thanks!

**Comment by QueerCodingGirl** [comment]
@ekohl when is the next release planned, or could you just craft a new release right now? I really dislike having to use my fork at the moment.

**Comment by ekohl** [comment]
We don't really plan releases. They go out as needed. I think we can prepare one.

**Comment by ekohl** [comment]
It went out via https://github.com/voxpupuli/beaker-docker/pull/57. Thanks for your contribution!

**Pull request merged**
