### PR TITLE
set flag for container to container communication

### PR DESCRIPTION
**Pull request by rwaffen**
under the premisse that the beaker is runnning in a container and the test-container is on the same docker-deamon/on the same docker-host, we can set the nested docker flag and get in the condition that we are both are containers and can connect directly.

tested in our local gitlab with docker-runners

//cc @QueerCodingGirl 
Ref: #64 , #46

### CODE REVIEW

**Review by QueerCodingGirl — APPROVED** [review]

**Comment by bastelfreak** [comment]
@rwaffen can you please take one of our modules, for example puppet-collectd, update the Gemfile to use your beaker fork and create a PR? Then we can test if this change breaks existing setups.

**Comment by trevor-vaughan** [comment]
I'd like to ask that someone run this on a podman system as well before merging to make sure it doesn't break that stack.

**Comment by trevor-vaughan** [comment]
Update: The core tests passed so it's probably fine but I haven't checked to see if we do multi-node in that one yet.

**Comment by rwaffen** [comment]
i have no podman system at hand :(

**Comment by trevor-vaughan** [comment]
It looks like we may want to add a cross-host test to the internal `beaker` tests so that we don't have to worry about an external check.

**Comment by rwaffen** [comment]
so how do we proceed from here on?

**Comment by rwaffen** [comment]
@jay7x said in the slack, that podman ist also working for him

**Comment by trevor-vaughan** [comment]
The ideal method would be to add a test to https://github.com/voxpupuli/beaker-docker/blob/master/spec/beaker/hypervisor/docker_spec.rb that does some sort of verifiable communication between the two nodes.

SSH with a subcommand that echos something to a file or anything that we can throw between the two nodes that can be validated.

**Comment by rwaffen** [comment]
i don't know if we have this "node" concept in GHA. if you are talking docker-nodes as in a host with a running docker-daemon. or how do i have to understand this? this is way more complex than i thought it would be 😅

**Comment by trevor-vaughan** [comment]
Beaker spins up multiple simultaneous containers and they are addressable by hostname (check the `/etc/hosts` test in that file).

You should be able to add a test at the bottom of the file that loops through the hosts and tries to do something between them.

[This](https://github.com/simp/pupmod-simp-rsync/blob/master/spec/acceptance/suites/default/10_server_client_spec.rb) is probably an overcomplicated example but I can't think of a more straightforward one that I can link to at the moment. Will update if I think of one.

**Review by bastelfreak — APPROVED** [review]

**Comment by rwaffen** [comment]
@trevor-vaughan is this okay so? we starting beaker in a docker container and let is spawen the beaker-docker acceptance tests?

**Review by QueerCodingGirl — APPROVED** [review]

**Comment by rwaffen** [comment]
@bastelfreak is it okay to merge this? we tested it together and it works like intended.

**Pull request merged**
